_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 2
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size:
    value: 8
best_val_loss:
    value: 100
current_epoch:
    value: 0
dataset:
    value: Mixed
epochs_without_improvement:
    value: 0
loss:
    value: L1
model:
    value: UNet
num_epochs:
    value: 1000
optimizer:
    value: Adam
output_path:
    value: Outputs/
patience:
    value: 50
preprocessing_name:
    value: resize
preprocessing_size:
    value: 512
save_interval:
    value: 10
scheduler:
    value: CosineAnnealing
